# Clippy configuration
# https://doc.rust-lang.org/nightly/clippy/lint_configuration.html

avoid-breaking-exported-api = false
disallowed-names = []
disallowed-methods = [
    # https://internals.rust-lang.org/t/synchronized-ffi-access-to-posix-environment-variable-functions/15475
    { path = "std::env::remove_var", reason = "this function should be considered `unsafe`" },
    { path = "std::env::set_var", reason = "this function should be considered `unsafe`" },
]
